### ISSUE TITLE
Pythonic Grammar Suggestion

### ISSUE THREAD

**Issue by AmosJin** [Dorothy00/algorithm#1]
## Indent & Space

Set your vim configuration: set tab to be 2 space and the space in the end of the line should be delete automatically  when save the file.
## Pythonic
1. No ; symbol, all you lines end with ';', delete them.
2. In the SelectSort.py, line 19 ~ 21

```
min_data = data[j]
data[j] = data[i]
data[i] = min_data
```

That's redundant, just code `data[i], data[j] = data[j], data[i]`, that's how to do it in Python!

**Comment by Dorothy00** [comment]
got it...
